language: generic

ghc: 8.0

cache:
  directories:
    - ~/.stack
    - ~/.stack-work
    - $HOME/.stack
    - $HOME/.stack-work

install:
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --no-terminal --install-ghc test --only-dependencies

script:
  - stack --no-terminal test --haddock --no-haddock-deps
